/* DO NOT EDIT THIS FILE */

#include <stdbool.h>
#include <stdlib.h>
#include <time.h>

#include <GL/glew.h>
#include <GL/glut.h>
#include <GL/glxew.h>

#include <GL/freeglut_ext.h>

#include "log.h"
#include "image.h"
#include "display.h"
#include "texture.h"

#define WIDTH 640
#define HEIGHT 360


typedef struct display
{
    unsigned int width;
    unsigned int height;
    unsigned int window_id;

    image_dir_t* image_dir;
    texture_t*  texture;
    bool enabled;

} display_t;


static display_t* display =  NULL;


int display_init(image_dir_t* image_dir)
{
    if (display != NULL)
    {
        LOG_ERROR("display has already been initialised");
        goto fail_exit;
    }

    display = malloc(sizeof(display_t));

    display->width = WIDTH;
    display->height = HEIGHT;
    display->window_id = 0;

    display->image_dir = image_dir;
    display->texture = malloc(sizeof(texture_t));
    display->enabled = true;

    return 0;

fail_exit:
    return -1;
}

void display_destroy()
{
    if (display != NULL)
    {
        free(display);
        display = NULL;
    }
}

static int pre_display()
{
    if (display == NULL)
    {
        LOG_ERROR("display has not been initialised");
        goto fail_exit;
    }

    glViewport(0, 0, display->width, display->height);
    if (LOG_ERROR_OPENGL("glViewport") < 0) {
        goto fail_exit;
    }

    glMatrixMode(GL_PROJECTION);
    if (LOG_ERROR_OPENGL("glMatrixMode") < 0) {
        goto fail_exit;
    }

    glLoadIdentity();
    if (LOG_ERROR_OPENGL("glLoadIdentity") < 0) {
        goto fail_exit;
    }

    gluOrtho2D(0.0, 1.0, 0.0, 1.0);

    glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
    if (LOG_ERROR_OPENGL("glClearColor") < 0) {
        goto fail_exit;
    }

    glEnable(GL_BLEND);
    glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);


    glClear(GL_COLOR_BUFFER_BIT);
    if (LOG_ERROR_OPENGL("glClear") < 0) {
        goto fail_exit;
    }

    return 0;

fail_exit:
    return -1;
}

static int render()
{
    if (display == NULL)
    {
        LOG_ERROR("display has not been initialised");
        goto fail_exit;
    }

    if (display->image_dir == NULL)
    {
        LOG_ERROR_NULL_PTR();
        goto fail_exit;
    }


     /*if (display->texture == 0) {
        glGenTextures(1, &display->texture);
        if (LOG_ERROR_OPENGL("glGenTextures") < 0) {
            goto fail_exit;
        }
    }*/

    image_t* image = NULL;
    if (display->enabled && (image = image_dir_load_next(display->image_dir)) != NULL) {

        if(image == NULL)
        {
            LOG_ERROR_NULL_PTR();
            goto fail_exit;
        }

        display->texture = init_texture(image);
        if(display->texture == NULL)
        {
            LOG_ERROR_NULL_PTR();
            goto fail_exit;
        }


        /*glBindTexture(GL_TEXTURE_2D, display->texture);
        if (LOG_ERROR_OPENGL("glBindTexture") < 0) {
            goto fail_exit;
        }

        glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, image->width, image->height, 0, GL_RGBA,
                     GL_UNSIGNED_BYTE, image->pixels);
        if (LOG_ERROR_OPENGL("glTexImage2D") < 0) {
            goto fail_exit;
        }

        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
        if (LOG_ERROR_OPENGL("glTexParameteri") < 0) {
            goto fail_exit;
        }

        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
        if (LOG_ERROR_OPENGL("glTexParameteri") < 0) {
            goto fail_exit;
        }

        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP);
        if (LOG_ERROR_OPENGL("glTexParameteri") < 0) {
            goto fail_exit;
        }

        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP);
        if (LOG_ERROR_OPENGL("glTexParameteri") < 0) {
            goto fail_exit;
        }*/

        glEnable(GL_TEXTURE_2D);
        if (LOG_ERROR_OPENGL("glEnable") < 0) {
            goto fail_exit;
        }

        glBegin(GL_QUADS);
        glTexCoord2d(0.0, 0.0);
        glVertex2d(0.0, 0.0);
        glTexCoord2d(1.0, 0.0);
        glVertex2d(1.0, 0.0);
        glTexCoord2d(1.0, 1.0);
        glVertex2d(1.0, 1.0);
        glTexCoord2d(0.0, 1.0);
        glVertex2d(0.0, 1.0);
        glEnd();

        if (LOG_ERROR_OPENGL("glBegin / glEnd") < 0) {
            goto fail_exit;
        }

        glClear(GL_COLOR_BUFFER_BIT);
        if (LOG_ERROR_OPENGL("glClear") < 0) {
            goto fail_exit;
        }
    }

    return 0;

fail_exit:
    return -1;
}


static inline void post_display() {
    glutSwapBuffers();
}

static void callback_display() {
    if (pre_display() < 0) {
        LOG_ERROR("pre-display failed");
    }

    if (render() < 0) {
        LOG_ERROR("display failed");
    }

    post_display();
}

static void callback_idle() {
    glutSetWindow(display->window_id);
    glutPostRedisplay();
}


void callback_keyboard(unsigned char key, int x, int y) {
    if (display == NULL) {
        LOG_ERROR("viewer has not been initialised");
        return;
    }

    switch (key) {
    case 'q':
        printf("Closing application\n");
        glutLeaveMainLoop();
        break;

    case '1':
        printf("Selected serial implementation\n");
        break;

    case '2':
        printf("Selected openmp implementation\n");
        break;

    case '3':
        printf("Selected opencl implementation\n");
        break;
        
    case ' ':
        printf("Rendering %s\n", display->enabled ? "disabled" : "enabled");
        display->enabled = !display->enabled;
        break;

    default:
        break;
    }
}

static void callback_reshape(int width, int height) {
    glutSetWindow(display->window_id);
    glutReshapeWindow(width, height);

    display->width  = width;
    display->height = height;
}

int display_open() {
    if (display == NULL) {
        LOG_ERROR("display has not been initialised");
        goto fail_exit;
    }

    glutInitDisplayMode(GLUT_RGBA | GLUT_DOUBLE);
    

    int x_pos = (glutGet(GLUT_SCREEN_WIDTH) - display->width) / 2;
    int y_pos = (glutGet(GLUT_SCREEN_HEIGHT) - display->height) / 2;

    glutInitWindowPosition(x_pos, y_pos);
    glutInitWindowSize(display->width, display->height);
    display->window_id = glutCreateWindow("image_resultat");

    glutDisplayFunc(callback_display);
    glutIdleFunc(callback_idle);
    glutKeyboardFunc(callback_keyboard);

    glutReshapeFunc(callback_reshape);
    glewInit();
    glXSwapIntervalMESA(0);

    glutMainLoop();
    printf("7--------------- \n");

    return 0;

fail_exit:
    return -1;
}
