/* DO NOT EDIT THIS FILE */

#include <signal.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <GL/glut.h>

#include "image.h"
#include "log.h"
#include "display.h"

static void show_help(FILE* f, const char* exec_name) {
    fprintf(f, "Usage: %s [OPTION]...\n", exec_name);
    fprintf(f, "\n");
    fprintf(f, "Options:\n");
    fprintf(f, "  --directory PATH                path to read and write images\n");
    fprintf(f, "  --method [openmp|opencl] method to use\n");
}

static void fail_missing_argument(const char* exec_name, const char* opt) {
    fprintf(stderr, "%s: option '%s' requires an argument\n", exec_name, opt);
    fprintf(stderr, "Try '%s --help' for more information.\n", exec_name);
    exit(1);
}

static void fail_unknown_argument(const char* exec_name, const char* opt) {
    fprintf(stderr, "%s: unrecognized option '%s'\n", exec_name, opt);
    fprintf(stderr, "Try '%s --help' for more information.\n", exec_name);
    exit(1);
}

static void fail_unknown_method_algorithm(const char* exec_name, const char* arg) {
    fprintf(stderr, "%s: unrecognized argument '%s' for option `--method`\n", exec_name, arg);
    fprintf(stderr, "Try '%s --help' for more information.\n", exec_name);
    exit(1);
}

/*static void fail_multiple_method(const char* exec_name) {
    fprintf(stderr, "%s: zero or one option `--method` must be specified\n", exec_name);
    fprintf(stderr, "Try '%s --help' for more information.\n", exec_name);
    exit(1);
}*/


static void run_viewer(image_dir_t* image_dir) {
    if (display_init(image_dir) < 0) {
        LOG_ERROR("failed to initialise display");
        exit(1);
    }

    if (display_open() < 0) {
        LOG_ERROR("failed to open display");
        exit(1);
    }

    display_destroy();
}

static image_dir_t image_dir = {.load_current = 0, .stop = false};

static void sigint_handler(int sig) {
    printf("\n\rSIGINT received, stopping method algorithm\n");
    image_dir.stop = true;
}

int main(int argc, char* argv[]) {

    if (getenv("DISPLAY") != NULL) {
        glutInit(&argc, argv);
    }


    char* exec_name = argv[0];
    bool use_method_openmp = false;
    bool use_method_opencl = false;

    for (int i = 1; i < argc; i++) {
        if (strcmp("--directory", argv[i]) == 0) {
            if (i > argc - 1) {
                fail_missing_argument(exec_name, argv[i]);
            }

            image_dir.name = argv[++i];
        } else if (strcmp("--method", argv[i]) == 0) {
            if (i > argc - 1) {
                fail_missing_argument(exec_name, argv[i]);
            }

            if (strcmp("openmp", argv[i + 1]) == 0) {
                use_method_openmp = true;
            } else if (strcmp("opencl", argv[i + 1]) == 0) {
                use_method_opencl = true; 
            } else {
                fail_unknown_method_algorithm(exec_name, argv[i + 1]);
            }

            i++;
        } else if (strcmp("--help", argv[i]) == 0) {
            show_help(stdout, exec_name);
            exit(0);
        } else {
            fail_unknown_argument(exec_name, argv[i]);
        }
    }

    if (signal(SIGINT, sigint_handler) == SIG_ERR) {
        LOG_ERROR_ERRNO("signal");
        exit(1);
    }

    printf("Starting viewing image, press CTRL+C to stop loading images\n");

    if (use_method_openmp) {
        image_dir.save_prefix = "openmp";
       
    } else if (use_method_opencl) {
        image_dir.save_prefix = "opencl";
        run_viewer(&image_dir);
       
    } else {
        LOG_ERROR("no method configured");
        exit(1);
    }

    return 0;

}