/* DO NOT EDIT THIS FILE */

#include <fcntl.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

#include "log.h"
#include "opencl.h"


char* opencl_kernel_path = NULL;


static char* getPath()
{
    char* path = NULL;

    if (opencl_kernel_path != NULL)
    {
        if(access(opencl_kernel_path, F_OK) < 0)
        {
            LOG_ERROR("file %s  cannot be accessed  ", opencl_kernel_path);
            goto fail_exit;
        }

        path = opencl_kernel_path;
    }


    if (path == NULL)
    {
        if(access(__KERNEL_FILE__, F_OK) < 0)
        {
            LOG_ERROR("file %s cannot be accessed", __KERNEL_FILE__);
            goto fail_exit;
        }

        path =__KERNEL_FILE__;
    }

    return path;

fail_exit:
    return NULL;
}


int opencl_load_kernel_code(char** code, size_t* len){

}
