/* DO NOT EDIT THIS FILE */

#include <fcntl.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

#include "log.h"
#include "opencl.h"


void sayHello()
{
    printf("hello world \n");
}
