/* DO NOT EDIT THIS FILE */

#ifndef INCLUDE_DISPLAY_H_
#define INCLUDE_DISPLAY_H_

#include "image.h"

int display_init(image_t* image);
void display_destroy();
int display_open();

#endif /* INCLUDE_DISPLAY_H_ */