/* DO NOT EDIT THIS FILE */

#pragma once

#ifndef INCLUDE_TEXTURE_H_
#define INCLUDE_TEXTURE_H_

#include <GL/glew.h>
#include "image.h"
#include "pixel.h"
#include "log.h"
#include <time.h>
#include <stdbool.h>
#include <stdlib.h>

class Texture 
{
private:
    GLuint texture_id;
    pixel_t* pixels;
    unsigned int width;
    unsigned int height;
    unsigned char* buffer;

public:
    Texture(image_t* image);
    ~Texture();

    int Bind(unsigned int slot = 0) const;
    void Unbind() const;
};

#endif /*INCLUDE_TEXTURE_H_*/